/* eslint-disable no-multi-str */
// every single question from the application process
const ApplicationQuestions: { [key: number]: string } = {
    1: "If given a choice, what would you like to be called?",
    2: "It is important to consult a physician before starting an Aperture Science Enrichment Center program. If one or more of the statements listed below applies to you, please contact your supervisor to secure permission to consult a physician before beginning an Enrichment Center program. Pick the condition that most applies to you.",
    3: "Sally, Dwayne, Anthony, David, and Franklin are, collectively, exactly 10 years apart in age. Sally's is two years older than David. David's favorite letter is 'g'. Anthony's favorite letter is also 'g', but Dwayne has no preference, insisting that he likes all the letters equally except for 's'. What is Franklin's favorite letter?",
    4: "Which of the following best describes your pain?",
    5: "What is your favorite color?",
    6: "How do others describe your education?",
    7: "What is your current living situation?",
    8: "Do you require any jewelry for health reasons?",
    9: "Do you require socks to be part of your uniform?",
    10: "Do you prefer long or short sleeves?",
    11: "Does your illness prevent you from working?",
    12: "Not including periods of mandatory silence, what is the longest you have gone voluntarily without talking?",
    13: "Do you require music to perform simple tasks?",
    14: "Your favorite color is:",
    15: "Lying about my favorite color makes me feel:",
    16: "Are you plagued by suspicions that other people, including coworkers and relatives, may be doing things behind your back that will hurt you?",
    17: "What is your favorite meal?",
    18: "Which pre-Christian mathematician is not correctly matched to his home city?",
    19: "Please choose the description that best describes your personality:",
    20: "A cake can be sliced into more than seven pieces by making only four diameter cuts through its center.",
    21: "Other than a large egret, what wild animal would you like to domesticate? NOTE: Several choices, including, but not limited to, 'Large Egret', may trigger an investigation. Your supervisor has no further information about instigating animals or the investigatory process, though, upon request, your supervisor can provide further details about their authorized prophylactic unfamiliarity with procedure.",
    22: "Which interrogation technique do you think would be most effective on you?",
    23: "Have you experienced recurrent thoughts of regicide?",
    24: "If you answered 'yes' to the previous question, please rate the following statement: I know what 'regicide' means.",
    25: "You are a liar:",
    26: "Can you flash your ROM?",
    27: "Please acknowledge before continuing:\
    \
    I understand that my responses to all items in this questionnaire are the property of Aperture Science. As such, they will remain strictly confidential, though they may be used to distribute prizes and/or initiate, prolong, or modify the invasive properties of authorized questioning, investigation, testing, and surveillance.",
    28: "Are you functionally incapacitated by witnessing other people's misery?",
    29: "Do you get pleasure from solitary pursuits?",
    30: "What is your favorite flatware for, purely as an example, eating cake?",
    31: "What is your favorite number between 31 and 37?",
    32: "Do you trust yourself?",
    33: "In case you forget your UIN(+L) and need to retrieve it later, please list a crime that only you would know that you have committed:",
    34: "How often do you exercise?",
    35: "If you disappeared tomorrow would anyone miss you?",
    36: "Would you like to use a prism to study light?",
    37: "Do you feel depressed, guilty, or remorseful?",
    38: "Do you ever have feelings that people are talking about you or watching you?",
    39: "Rate the pain you have been able to withstand without losing consciousness:",
    40: "Complete the following statement with the answer that DOES NOT apply to you:\
    I am often:",
    41: "On a scale of 12 to 11, with the 12 possible choices arranged as on the face of a clock, how would you rate your awareness of any habitual physical mannerisms such as tugging your ear or hair, eye twitches, hand spasms, etc.?",
    42: "First Pet's Name:",
    43: "Do you regularly experience deja vu?",
    44: "Complete this sentence,",
    45: "Do you feel bad that you have let your coworkers and/or larger mandated collective down?",
    46: "Pick the sentence that incorrectly employs the word 'excruciating'.",
    47: "Choose the correct inspiration for this inspirational phrase, “You can succeed best and quickest by going it alone.”",
    48: "I express my opinions, even if others in the group disagree with me:",
    49: "Pick your favorite type of cake.",
    50: "Gender"
}

export default ApplicationQuestions;